jobs:
  auto-code-format:
    env:
      BRANCH_NAME: ${{ github.head_ref || github.ref_name }}
      SHA: ${{ github.sha }}
    if: ${{ startsWith(github.repository, 'apache/') }}
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      if: github.event_name == 'pull_request' && github.event.action == 'closed' &&
        github.event.pull_request.merged == true
      name: Checkout
      uses: actions/checkout@v3
    - continue-on-error: true
      name: Set up JDK 8
      uses: actions/setup-java@v2
      with:
        distribution: adopt
        java-version: '8'
    - continue-on-error: true
      name: Code Format Apply
      run: ./mvnw spotless:apply
    - continue-on-error: true
      name: Create Pull Request
      uses: peter-evans/create-pull-request@v4.1.1
      with:
        author: ${{ github.actor }} <${{ github.actor }}@users.noreply.github.com>
        base: ${{ env.BRANCH_NAME }}
        body: '## Code format apply

          - run the result of mvn spotless:apply

          '
        branch: ${{ env.BRANCH_NAME }}-${{ env.SHA }}
        commit-message: code format apply
        committer: GitHub <noreply@github.com>
        delete-branch: true
        labels: 'code format

          automated pr

          '
        signoff: false
        title: '[Code] Code format apply'
        token: ${{ secrets.GITHUB_TOKEN }}
name: Create Code Format Apply PullRequest
on:
  repository_dispatch:
    types: trigger-ga___auto-format-pr.yaml
