jobs:
  create-comment:
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      name: Create comment
      uses: actions-cool/issues-helper@v3
      with:
        actions: create-comment
        body: "## :blush:  Welcome to the Apache Linkis community!!\nWe are glad that\
          \ you are contributing by opening this issue.\n\nPlease make sure to include\
          \ all the relevant context.\nWe will be here shortly.\n\nIf you are interested\
          \ in contributing to our website project, please let us know!\nYou can check\
          \ out our contributing guide on\n :point_right:  [How to Participate in\
          \ Project Contribution](https://linkis.apache.org/community/how-to-contribute).\n\
          \n\n### Community\n\n|WeChat Assistant|WeChat Public Account|\n|-|-|\n|<img\
          \ src=\"https://linkis.apache.org/Images/wedatasphere_contact_01.png\" width=\"\
          128\"/>|<img src=\"https://linkis.apache.org/Images/gzh_01.png\" width=\"\
          128\"/>|\n\n\n### Mailing Lists\n|Name|Description|Subscribe|Unsubscribe|Archive|\n\
          |:-----|:--------|:------|:-------|:-----|\n| [dev@linkis.apache.org](mailto:dev@linkis.apache.org)\
          \ | community activity information | [subscribe](mailto:dev-subscribe@linkis.apache.org)\
          \ | [unsubscribe](mailto:dev-unsubscribe@linkis.apache.org) | [archive](http://mail-archives.apache.org/mod_mbox/linkis-dev)\
          \ |\n"
        issue-number: ${{ github.event.issue.number }}
        token: ${{ secrets.GITHUB_TOKEN }}
name: Create Comment
on:
  repository_dispatch:
    types: trigger-ga___auto-comment.yml
