jobs:
  build-frontend:
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v2
      with:
        submodules: true
    - continue-on-error: true
      uses: actions/cache@v2
      with:
        key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
        path: ~/.npm
        restore-keys: '${{ runner.os }}-node-

          '
    - continue-on-error: true
      name: Set Up NodeJS ${{ matrix.node-version }}
      uses: actions/setup-node@v2-beta
      with:
        node-version: ${{ matrix.node-version }}
    - continue-on-error: true
      name: Build frontend by node.js
      run: 'cd linkis-web

        npm install

        npm run build

        '
    strategy:
      matrix:
        node-version:
        - 16
name: Build Frontend
on:
  repository_dispatch:
    types: trigger-ga___build-frontend.yml
