jobs:
  apache-rat-check:
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      name: Checkout source
      uses: actions/checkout@v2
    - continue-on-error: true
      name: Set up JDK 8
      uses: actions/setup-java@v2
      with:
        distribution: adopt
        java-version: '8'
    - continue-on-error: true
      name: License check with Maven
      run: 'rat_file=`mvn apache-rat:check  | { grep -oe "\\S\\+/rat.txt" || true;
        }`

        echo "rat_file=$rat_file"

        if [[ -n "$rat_file" ]];then  echo "check error!" && cat $rat_file && exit
        123;else echo "check success!" ;fi

        '
    - continue-on-error: true
      name: Upload the report
      uses: actions/upload-artifact@v2
      with:
        name: license-check-report
        path: '**/target/rat.txt'
name: License Check
on:
  repository_dispatch:
    types: trigger-ga___check-license.yml
