jobs:
  spotless-check:
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      name: Checkout source
      uses: actions/checkout@v2
    - continue-on-error: true
      name: Set up JDK 8
      uses: actions/setup-java@v2
      with:
        distribution: adopt
        java-version: '8'
    - continue-on-error: true
      name: Code format check
      run: ./mvnw spotless:check
name: Code Format Check
on:
  repository_dispatch:
    types: trigger-ga___check-code-format.yml
