jobs:
  sql-check:
    runs-on: self-hosted
    services:
      postgres:
        env:
          POSTGRES_DB: linkis_test
          POSTGRES_PASSWORD: postgres
          POSTGRES_PORT: 5432
          POSTGRES_USER: postgres
        image: postgres:14
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s
          --health-retries 5
        ports:
        - 35432:5432
    steps:
    - continue-on-error: true
      name: Checkout source
      uses: actions/checkout@v2
    - continue-on-error: true
      name: Verify linkis init pg sql
      run: 'create_db_cmd=`PGPASSWORD=postgres psql -h 127.0.0.1 -p 35432 -U postgres
        -tc "SELECT ''CREATE DATABASE linkis_test;'' WHERE NOT EXISTS (SELECT FROM
        pg_database WHERE datname = ''linkis_test'');"`

        PGPASSWORD=postgres psql -h 127.0.0.1 -p 35432 -U postgres -d linkis_test
        -tc "${create_db_cmd}"

        PGPASSWORD=postgres psql -h 127.0.0.1 -p 35432 -U postgres -d linkis_test
        -tc "CREATE SCHEMA IF NOT EXISTS linkis_test;"

        PGPASSWORD=postgres PGOPTIONS="--search_path=linkis_test" psql -h 127.0.0.1
        -p 35432 -U postgres -d linkis_test -f ./linkis-dist/package/db/linkis_ddl_pg.sql

        PGPASSWORD=postgres PGOPTIONS="--search_path=linkis_test" psql -h 127.0.0.1
        -p 35432 -U postgres -d linkis_test -f ./linkis-dist/package/db/linkis_dml_pg.sql

        PGPASSWORD=postgres PGOPTIONS="--search_path=linkis_test" psql -h 127.0.0.1
        -p 35432 -U postgres -d linkis_test -tc "\dt"'
name: Postgresql Script Check
on:
  repository_dispatch:
    types: trigger-ga___check-sql-pg-script.yml
