jobs:
  dead-links-check:
    if: (github.repository == 'apache/linkis')
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v3
    - continue-on-error: true
      uses: gaurav-nelson/github-action-markdown-link-check@v1
      with:
        config-file: .github/workflows/dlc.json
        folder-path: ../
        use-quiet-mode: no
        use-verbose-mode: yes
    timeout-minutes: 30
name: Dead Link Check
on:
  repository_dispatch:
    types: trigger-ga___dead-link-checker.yaml
