jobs:
  publish-snapshot:
    if: ${{ startsWith(github.repository, 'apache/') }}
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      name: Checkout repository
      uses: actions/checkout@v2
      with:
        ref: ${{ matrix.branch }}
    - continue-on-error: true
      name: Setup JDK 8
      uses: actions/setup-java@v2
      with:
        distribution: adopt
        java-version: 8
    - continue-on-error: true
      id: get_version
      name: Get Version
      run: 'BRANCE="${{ matrix.branch }}"

        echo "::set-output name=version::${BRANCE#*-}-SNAPSHOT"

        '
    - continue-on-error: true
      env:
        ASF_PASSWORD: ${{ secrets.NEXUS_PW }}
        ASF_USERNAME: ${{ secrets.NEXUS_USER }}
      name: Publish snapshot - ${{ matrix.branch }}
      run: './mvnw versions:set -Drevision={{steps.get_version.outputs.version}} -DgenerateBackupPoms=false

        ./mvnw deploy -s  ./.github/asf-settings.xml -Dmaven.test.skip=true -Dmaven.javadoc.skip=true  -DretryFailedDeploymentCount=10'
    strategy:
      fail-fast: false
      matrix:
        branch:
        - dev-1.5.0
name: Publish Snapshot
on:
  repository_dispatch:
    types: trigger-ga___publish-snapshot.yml
